version: '3'
networks:
  app-tier:

services:

  hello-world:
    image: hello-world
    ports:
      - '8080:8080'
    environment:
      - DATABASE_HOST=obcmysqldb
      - DATABASE_USER=user
      - DATABASE_PASSWORD=user123
      - DATABASE_NAME=obcdb
      - DATABASE_PORT=3306
    networks:
      - app-tier
    depends_on:
      - "tophathellodb"

  tophathellodb:
    image: mysql:8
    networks:
      - app-tier
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user123
      - MYSQL_ROOT_PASSWORD=user123
      - MYSQL_DATABASE=obcdb
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - tophathellodb:/var/lib/mysql

volumes:
  tophathellodb:
