version: '3'
networks:
  hello-network:

services:
  hello-world:
    image: hello-world
    ports:
      - "9080:9080"
    networks:
      - hello-network
    depends_on:
      - tophathellodb

  tophathellodb:
    image: mysql:8
    networks:
      - hello-network
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user123
      - MYSQL_ROOT_PASSWORD=user123
      - MYSQL_DATABASE=hellosqldb
    ports:
      - 3306:3306
    expose:
      - '3306'
